### ISSUE TITLE
Implement ing with cpu

### ISSUE THREAD

**Issue by dilya22** [yuxiangsun/RTFNet#11]
Dear Dr. Yuxiang Sun,
I would like to implement this very meaningful project into a machine that runs only with CPU.
Could you please share your take on this issue, regarding feasibility of implementing it using CUDA toolkit without gpu or converting gpu arrays into cpu 
arrays andd its effect on computation time?
Thank you in advance!

**Comment by yuxiangsun** [comment]
> Dear Dr. Yuxiang Sun,
> I would like to implement this very meaningful project into a machine that runs only with CPU.
> Could you please share your take on this issue, regarding feasibility of implementing it using CUDA toolkit without gpu or converting gpu arrays into cpu
> arrays andd its effect on computation time?
> Thank you in advance!

To run on CPU, please delete `.cuda(args.gpu)` .
