### ISSUE TITLE
Results of NTE and NRE

### ISSUE THREAD

**Issue by xingchenzhang** [yuxiangsun/RTFNet#12]
Hi,

Thank you very much for your nice work!

I have a question about the result of NTE and NRE shown in Table IV of the paper.

When you test NTE and NRE, did you retrain the model? Or simple remove RGB encoder or thermal encoder from RTFNet model?

I have tried to remove the RGB encoder to have NTE, and remove the thermal encoder to obtain NRE. But in my case, the macc of NTE at daytime is only 27.3, and the macc of NTE at nighttime is only 16.1. The macc of NRE at daytime is only 11.1, and the macc of NRE at nighttime is only 11.1.

Therefore, I am wondering how you guys produced the results in Table IV. Could you please give some explanations?

Bests,
Xingchen

**Comment by Parv-Maheshwari** [comment]
@xingchenzhang  @yuxiangsun  can you tell what was the conclusion for this. Also, @yuxiangsun ,  if possible, can you share the  NRE model files ? Thank you

**Comment by wylbd** [comment]
Thank you for your letter. i will reply your letter as soon as I can! best wishes!
yours sincerelyYulun Wu?xml:namespace> 
Department of Mechanical Engineering,Zhejiang University
