### ISSUE TITLE
训练耗时问题

### ISSUE THREAD

**Issue by LZYmixiu** [yuxiangsun/RTFNet#14]
请问您训练这个网络花了多久时间？最终训练了多少个epoch？每100个需要多久？
我这里每训练一个epoch需要花费1个小时左右（batch size = 2 num_workers= 0），耗时太长让我很困惑，想知道这个时间是否是正常范围？

**Comment by yuxiangsun** [comment]
取决于你用的GPU

**Comment by LZYmixiu** [comment]
> 取决于你用的GPU

我对您在FuseSeg的后续工作也很感兴趣，是否有分享代码的计划呢？
如果您能发我一份更是感激不尽，我的邮箱：2424967522@qq.com
