### ISSUE TITLE
a question about dataset

### ISSUE THREAD

**Issue by lvcat** [yuxiangsun/RTFNet#2]
another question...
 i downloaded the ir_seg_dataset but the pics show rgb type in a software and ir in another software. and the label folder pics r all almost black. is it normal? if it isnt. would u mind share the dataset with me. thanks QAQ

**Comment by yuxiangsun** [comment]
“label folder pics r all almost black”: This is because the pixel value is the class number (e.g. 1, 2, 3..).  

We will release the prepossessed dataset (including the visualization for ground truth) along with the code.

**Comment by lvcat** [comment]
thx~

**Comment by lvcat** [comment]
i checked the pics inlabel folder it looks all 0= = with shape (480,640,3)  i m going to read that paper carefully. thx for ur answer. im grateful about it.

**Comment by lvcat** [comment]
i use pil instead opencv then got 4 channel. thx
