### ISSUE TITLE
Some problems about test result

### ISSUE THREAD

**Issue by WeianMao** [yuxiangsun/RTFNet#5]
First of all, thank you for your code. However, I downloaded your software and tried to train again, but i got wrong result, and i don’t why it happened. 
My test result is that: Miou: 51.4899%(resnet152) 48.20%(resnet101) 40.5% (resnet34) 45%(resnet18).
I have trained those model for about 140 to 180 epoch. I think that it is enough. So do you have any idea about this problem? Is it caused by dropout? Thank you very much.
![2C9FB2AA-27E6-44BB-9389-1F339C4F76D5](https://user-images.githubusercontent.com/49094689/63261451-1b567c80-c2b6-11e9-87cd-fb5f8d4cbe0b.jpeg)
![Uploading 9710B203-6C47-40C6-B8B1-0715FC292038.jpeg…]()
![Uploading 5FF7290A-C9BF-4648-BE7F-5FC1EDBA5870.jpeg…]()
![Uploading 49632F72-06E1-4BC2-9142-360780F9253C.jpeg…]()

**Comment by yuxiangsun** [comment]
Have you changed the layer numbers in `RTFNet.py` ?

**Comment by WeianMao** [comment]
Do You mean num_resnet_layers? Yes i changed this

**Comment by WeianMao** [comment]
Drop_last should equal to false, right?

**Comment by WeianMao** [comment]
> Have you changed the layer numbers in `RTFNet.py` ?

Do You mean num_resnet_layers? Yes i changed this

Drop_last should equal to false, right?

**Comment by yuxiangsun** [comment]
Just using the `train.py` is OK. You could not get exactly the same results, because every training process is unique. In addition, you may get results better or worse than those in the paper due to the randomness in the training process.

**Comment by WeianMao** [comment]
But i think the difference between my result and your result is too significant. For example, I got 40.5% Miou with resnet34, while this result on your paper is about 26%. How do you think about this? Is it normal and reasonable? So I think I got something wrong. Thank you very much!

**Comment by WeianMao** [comment]
> Just using the `train.py` is OK. You could not get exactly the same results, because every training process is unique. In addition, you may get results better or worse than those in the paper due to the randomness in the training process.

But i think the difference between my result and your result is too significant. For example, I got 40.5% Miou with resnet34, while this result on your paper is about 26%. How do you think about this? Is it normal and reasonable? So I think I got something wrong. Thank you very much!

**Comment by yuxiangsun** [comment]
This is my parameter setting for training RTFNet-34. Just for your reference.

 ```
    parser = argparse.ArgumentParser(description='Train with pytorch')   
#############################################################################################
    parser.add_argument('--model_name',  '-M',  type=str, default='RTFNet')
    parser.add_argument('--batch_size',  '-B',  type=int, default=10)
    parser.add_argument('--lr_start',  '-LS',  type=float, default=0.01)
    parser.add_argument('--gpu',        '-G',  type=int, default=0)
    #############################################################################################
    parser.add_argument('--lr_decay', '-LD', type=float, default=0.95)
    parser.add_argument('--epoch_max' ,  '-E',  type=int, default=100000) # please stop training mannully 
    parser.add_argument('--epoch_from',  '-EF', type=int, default=0) 
    parser.add_argument('--num_workers', '-j',  type=int, default=8)
    args = parser.parse_args()
```

**Comment by WeianMao** [comment]
OK， thank you very much
