### ISSUE TITLE
关于白天夜晚数据的问题

### ISSUE THREAD

**Issue by shi-xingping** [yuxiangsun/RTFNet#6]
您好 最近研读了您的论文 我注意到单独用白天跟夜晚的数据得到的结果（macc miou）比总体的都低， 理论上 总体的值不应该介于两者之间吗？ 这一点让我非常困惑，希望您能给一些指导。。。

**Comment by yuxiangsun** [comment]
因为不同的dataset，算出来的混淆矩阵是不一样的。mAcc和mIoU是在某一个dataset整体上算出来的。你可以自己弄几个toy example测试一下就明白了。

**Comment by yuxiangsun** [comment]
A toy example:
![image](https://user-images.githubusercontent.com/16552207/65009946-fe5aab00-d940-11e9-92f0-a3e9a587e7f1.png)

**Comment by shi-xingping** [comment]
非常感谢~~~

**Comment by shi-xingping** [comment]
但是比如第一个算出来是0.372  第二个矩阵0.211 将它们加起来以后算出来的值为0.3184还是在这两个数之间 但是论文里无论是白天还是夜晚的都比加起来的低。 我知道不会是平均值 但是不应该在这两个数之间吗

**Comment by yuxiangsun** [comment]
Not necessarily. You can simply verify it by setting the elements in the second matrix to extreme values, such as [[0, 0], [0, 64]].

**Comment by shi-xingping** [comment]
wonderful
谢谢啦
